### ISSUE TITLE
ACK! :) Any consideration when using HA alertmanager? 

### ISSUE THREAD

**Issue by dannyk81** [prymitive/kthxbye#15]
I've been following the linked AM issue for a while and seeing that it goes nowhere was contemplating to write something similar and then this came out, bravo!

Didn't try it yet, but was wondering if there's any consideration when running alertmanager in HA setup? should this sidecar be attached to both? one of?

Any advice?

**Comment by prymitive** [comment]
I think that you need to run a single instance against the entire cluster. Otherwise both might try to extend same silence and you end up with duplicates.

**Comment by dannyk81** [comment]
thanks, make sense!
