### ISSUE TITLE
kthxbye is eating up memory

### ISSUE THREAD

**Issue by oliverdawid** [prymitive/kthxbye#292]
We are using prometheus to monitor battery state of iot devices. We are running kubernetes 1.20 cluster and use kthxbye:latest to acknowledge those battery alarms. As these alarms tend to last quite long until they are done (might take several days), the alertmanager has quite a lot silences (in different states, most of them expired).

We see that kthxbye is eating up memory. Starting with 128MB limit we now need to go up to 512 MB and I cannot see some stabilization.

I tried to get intervals longer so we don't produce such a lot of expired silences but it is still a lot (we can see this by opening the website of alertmanager. It takes quite a time to get anything displayed).

Yesterday system kthxbye stopped working without any syslog output. So a ton of alarms fired until I restarted kthxbye and ACKed all alarms.

My parameters:
-alertmanager.uri http://prometheus-alertmanager.kube-system:80
-extend-with-prefix 'ACK: '
-extend-by 900s
-extend-if-expiring-in 90s
-interval 60s

Where shall I start debugging?

**Comment by prymitive** [comment]
How many alerts do you have in alertmanager?

alertmanager_alerts metric should tell you

**Comment by oliverdawid** [comment]
Alertmanager currently hold 55 alerts (all silenced)
Silences: 72190 expired

**Comment by prymitive** [comment]
72k is a lot of JSON to parse, it would explain high memory usage.
I should switch API read operations to use go streaming decoder, should be fairly simple. The problem is that standard go json parsing reads entire response body into memory and then parses into a struct, so it eats more memory with big responses.
Will look into when I have a moment.

**Comment by oliverdawid** [comment]
I think as you project is recommended e.g. in Karma this might be a good choice to implement it this way, as other might run into same problem.

**Comment by prymitive** [comment]
#297 should fix this and keep memory usage flat, it shouldn't grow with the number of alerts/silences

**Comment by prymitive** [comment]
This change is included in [v0.13-rc1](https://github.com/prymitive/kthxbye/releases/tag/v0.13-rc1)

**Comment by prymitive** [comment]
@oliverdawid please let me know if memory usage got better with 0.13-rc1 and I'll tag a final 0.13

**Comment by oliverdawid** [comment]
Happy new year Lukasz,

I looks like your code is working like a charm. We have quite a lot of incidents again but we don't encounter any memory problem yet. We only have about 20k incidents though but memory footprint is ridiculous small.

We did not encounter any other issue.

**Comment by prymitive** [comment]
https://github.com/prymitive/kthxbye/releases/tag/v0.13

**Comment by prymitive** [comment]
There was a bug that would cause silences to not be extend, fixed that and released https://github.com/prymitive/kthxbye/releases/tag/v0.14 so make sure to use that version
