### ISSUE TITLE
Basic auth functionality not working

### ISSUE THREAD

**Issue by xafer337** [prymitive/kthxbye#449]
Hi!

I'm trying to use the basic auth functionality, but it keeps crashing:

![image](https://user-images.githubusercontent.com/61606830/212318882-049baddb-32b9-448c-943f-db3998ac0fca.png)

I'm using this configuration in Docker (docker-compose):

![image](https://user-images.githubusercontent.com/61606830/212323134-843512ad-42ce-41a9-90e7-1f5080b04ee6.png)

It runs correctly when I remove the basic auth from my alertmanager and I remove "user:pasword@" from the uri on the configuration.
If I keep the basic auth on the uri config (it doesn't matter if the pass is incorrect), it crashes with the first error. I asume there is something wrong happening with the "alertmanager.uri" command.

Did I miss any configuration?

Thanks!

**Comment by prymitive** [comment]
Should be fixed in v0.16
